//! One module per rule. Each rule's intent, contract and allow-list schema: DESIGN.md.
//! The module list is generated by build.rs from the files in this directory.
include!(concat!(env!("OUT_DIR"), "/rule_mods.rs"));
