#!/usr/bin/env bash
# test-conf-registry-parity.sh (sp-g3uwp) — conf_key_parity cannot fail by construction: the
# allowlist conf.sh actually sources IS the registry's directory listing, generated by
# conf-gen.sh. This suite asserts that equality directly, rather than trusting it by
# inspection, and exercises conf-gen.sh's two refusals (an empty/missing registry; a
# dependency cycle among generated defaults) as positive controls.
#
# covers: spira/conf-gen.sh, spira/conf.d/
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
. "$HERE/testlib.sh"

echo "test-conf-registry-parity.sh"

TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT INT TERM

# =============================================================================
echo
echo "the generated allowlist is exactly the registry's directory listing:"
# =============================================================================
# A WRITABLE COPY, not the real $HERE in place: conf-gen.sh's output lands beside conf.sh,
# and the tree under test here may be mounted read-only for whoever runs this suite (the
# gate's container among them) — reading the registry never needs write access, only
# regenerating it does, so only the regeneration below moves to a scratch copy.
registry_keys="$(ls "$HERE/conf.d" | LC_ALL=C sort)"
registry_count="$(printf '%s\n' "$registry_keys" | sed '/^$/d' | wc -l)"

SCRATCH_SPIRA="$TMP/spira"; mkdir -p "$SCRATCH_SPIRA"
cp -r "$HERE/conf.d" "$SCRATCH_SPIRA/conf.d"
cp "$HERE/conf-gen.sh" "$SCRATCH_SPIRA/conf-gen.sh"
cp "$HERE/conf.sh" "$SCRATCH_SPIRA/conf.sh"

bash "$SCRATCH_SPIRA/conf-gen.sh" >/dev/null 2>"$TMP/gen.err"
wantrc "conf-gen.sh exits 0 against a writable copy of the real registry" 0 "$?"

generated_keys="$(grep -v '^#' "$SCRATCH_SPIRA/conf.d.keys.generated.sh" | tr -s ' ' '\n' \
    | sed -n '/^[A-Z_][A-Z0-9_]*$/p' | LC_ALL=C sort)"
generated_count="$(printf '%s\n' "$generated_keys" | sed '/^$/d' | wc -l)"

is "registry file count equals generated allowlist count" "$registry_count" "$generated_count"
is "registry listing is byte-identical to the generated allowlist (sorted)" \
    "$registry_keys" "$generated_keys"

# =============================================================================
echo
echo "conf.sh's own SPIRA_CONF_KEYS, sourced fresh (self-heal from nothing), matches too:"
# =============================================================================
rm -f "$SCRATCH_SPIRA/conf.d.keys.generated.sh" "$SCRATCH_SPIRA/conf.d.defaults.generated.sh"
# An isolated HOME with no real spira.toml anywhere in its search path: conf.sh fails
# closed (by design, nothing to do with this bead) when a config file exists but
# spira-config is not resolvable, and this box's real $HOME has one.
ISOHOME="$TMP/isohome"; mkdir -p "$ISOHOME"
sourced_keys="$(env -i HOME="$ISOHOME" PATH="$PATH" \
    bash -c "cd '$SCRATCH_SPIRA/..' && . './spira/conf.sh' >/dev/null 2>&1; tr -s ' ' '\n' <<<\"\$SPIRA_CONF_KEYS\"" \
    | sed '/^$/d' | LC_ALL=C sort)"
is "conf.sh's resolved SPIRA_CONF_KEYS matches the registry" "$registry_keys" "$sourced_keys"

# =============================================================================
echo
echo "positive control — an empty registry is refused, not silently emptied:"
# =============================================================================
EMPTY="$TMP/empty-spira"
mkdir -p "$EMPTY/conf.d"
cp "$HERE/conf-gen.sh" "$EMPTY/conf-gen.sh"
bash "$EMPTY/conf-gen.sh" >"$TMP/empty.out" 2>"$TMP/empty.err"
wantrc "conf-gen.sh refuses an empty conf.d/" 1 "$?"
[ -e "$EMPTY/conf.d.keys.generated.sh" ]
wantrc "no allowlist is written for an empty registry" 1 "$?"

# =============================================================================
echo
echo "positive control — a dependency cycle between two keys' defaults is refused:"
# =============================================================================
CYCLE="$TMP/cycle-spira"
mkdir -p "$CYCLE/conf.d"
cp "$HERE/conf-gen.sh" "$CYCLE/conf-gen.sh"
cat > "$CYCLE/conf.d/SPIRA_ZZTEST_CYCLE_A" <<'EOF'
TYPE=string
GROUP=zztest
DOC=cycle fixture A
DEFAULT<<'SPIRA_CONF_DEFAULT_EOF'
    : "${SPIRA_ZZTEST_CYCLE_A:=$SPIRA_ZZTEST_CYCLE_B}"
SPIRA_CONF_DEFAULT_EOF
EOF
cat > "$CYCLE/conf.d/SPIRA_ZZTEST_CYCLE_B" <<'EOF'
TYPE=string
GROUP=zztest
DOC=cycle fixture B
DEFAULT<<'SPIRA_CONF_DEFAULT_EOF'
    : "${SPIRA_ZZTEST_CYCLE_B:=$SPIRA_ZZTEST_CYCLE_A}"
SPIRA_CONF_DEFAULT_EOF
EOF
bash "$CYCLE/conf-gen.sh" >"$TMP/cycle.out" 2>"$TMP/cycle.err"
wantrc "conf-gen.sh refuses a dependency cycle" 1 "$?"
want "the refusal names both keys in the cycle" "SPIRA_ZZTEST_CYCLE_A" "$(cat "$TMP/cycle.err")"
want "the refusal names both keys in the cycle" "SPIRA_ZZTEST_CYCLE_B" "$(cat "$TMP/cycle.err")"
[ -e "$CYCLE/conf.d.defaults.generated.sh" ]
wantrc "no defaults file is written when the dependency graph has a cycle" 1 "$?"

tl_summary
