#!/usr/bin/env bash
#
# test-lockfile-lint.sh — lockfile-lint.sh's own positive control.
#
# THE CASE (sp-4kws1). sp-47kq1 moved indexmap 2.6.0 -> 2.14.2 (edition2024) in Cargo.lock
# with no Cargo.toml edit — a local `cargo build` under a newer, unpinned toolchain had
# silently re-resolved the lockfile — and PR 361's build failed under the gate's pinned
# toolchain. lockfile-lint.sh refuses a Cargo.lock version bump that carries no matching
# Cargo.toml change.
#
# THE POSITIVE CONTROL IS FIRST (law-absence-needs-a-positive-control). A bumped Cargo.lock
# is planted in a scratch git repository, the lint is required to name it (SEEN RED), and
# only then is a clean diff's silence evidence of anything.
#
# tier: T0
# covers: spira/lockfile-lint.sh spira/gate-touched.sh Cargo.toml Cargo.lock rust-toolchain.toml
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd -P)"
. "$HERE/testlib.sh"

echo "test-lockfile-lint.sh"

TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT INT TERM

lock_at() { # lock_at <ver> -> a minimal Cargo.lock with one registry package at <ver>
    cat <<EOF
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "indexmap"
version = "$1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0000000000000000000000000000000000000000000000000000000000000000"

[[package]]
name = "fixture"
version = "0.1.0"
EOF
}

TOML_NO_MENTION='[workspace]
members = ["fixture"]
resolver = "2"
'

ROOT="$TMP/root"; mkdir -p "$ROOT/spira"
cp "$HERE/lockfile-lint.sh" "$ROOT/spira/lockfile-lint.sh"
git init -q -b main "$ROOT"
git -C "$ROOT" config user.email t@t; git -C "$ROOT" config user.name t

lint_at() { # lint_at <root> <base-ref>
    SPIRA_GATE_BASE="$2" bash "$1/spira/lockfile-lint.sh" 2>&1
}

printf '%s' "$TOML_NO_MENTION" > "$ROOT/Cargo.toml"
lock_at 2.6.0 > "$ROOT/Cargo.lock"
git -C "$ROOT" add .
git -C "$ROOT" commit -q -m init
BASE="$(git -C "$ROOT" rev-parse HEAD)"

echo "1. no SPIRA_GATE_BASE at all:"
out="$(bash "$ROOT/spira/lockfile-lint.sh" 2>&1)"; rc=$?
is   "no base: exits 0" "0" "$rc"
want "no base: says no diff to check" "no diff to check" "$out"

echo "2. a clean tree (Cargo.lock unchanged) is silent and green:"
out="$(lint_at "$ROOT" "$BASE")"; rc=$?
is "unchanged lock: exits 0" "0" "$rc"

echo "3. SEEN RED: a bump with no matching Cargo.toml change is refused:"
lock_at 2.14.2 > "$ROOT/Cargo.lock"
out="$(lint_at "$ROOT" "$BASE")"; rc=$?
is   "bumped, unmatched: refused" "1" "$rc"
want "and names the package" "indexmap" "$out"
want "and names both versions" "2.6.0" "$out"
want "and names both versions" "2.14.2" "$out"

echo "4. SEEN GREEN: the same bump, with Cargo.toml naming the package, passes:"
printf '%s\n%s\n' "$TOML_NO_MENTION" '# indexmap bumped for RUSTSEC-2026-0000' > "$ROOT/Cargo.toml"
out="$(lint_at "$ROOT" "$BASE")"; rc=$?
is "bumped, matched: exits 0" "0" "$rc"
printf '%s' "$TOML_NO_MENTION" > "$ROOT/Cargo.toml"   # restore

echo "5. a downgrade is not a bump:"
lock_at 2.0.0 > "$ROOT/Cargo.lock"
out="$(lint_at "$ROOT" "$BASE")"; rc=$?
is "downgrade: exits 0" "0" "$rc"

echo "6. a brand-new package (absent from base) is out of scope:"
{ lock_at 2.6.0; printf '\n[[package]]\nname = "new-crate"\nversion = "1.0.0"\n'; } > "$ROOT/Cargo.lock"
out="$(lint_at "$ROOT" "$BASE")"; rc=$?
is "new package, unmentioned: exits 0" "0" "$rc"

echo "7. NEGATIVE CONTROL: no Cargo.lock in the tree at all is a skip, not a refusal:"
NOLOCK="$TMP/nolock"; mkdir -p "$NOLOCK/spira"
cp "$HERE/lockfile-lint.sh" "$NOLOCK/spira/lockfile-lint.sh"
git init -q -b main "$NOLOCK"
git -C "$NOLOCK" config user.email t@t; git -C "$NOLOCK" config user.name t
printf 'x\n' > "$NOLOCK/x"; git -C "$NOLOCK" add .; git -C "$NOLOCK" commit -q -m init
NB="$(git -C "$NOLOCK" rev-parse HEAD)"
out="$(lint_at "$NOLOCK" "$NB")"; rc=$?
is   "no Cargo.lock: exits 0" "0" "$rc"
want "and says why" "no Cargo.lock in this tree" "$out"

echo "8. base with no Cargo.lock (added on this branch) is a skip:"
lock_at 2.6.0 > "$NOLOCK/Cargo.lock"
out="$(lint_at "$NOLOCK" "$NB")"; rc=$?
is   "lock added since base: exits 0" "0" "$rc"

# =========================================================================================
# GATE INTEGRATION. A fence nothing invokes is a file.
# =========================================================================================
echo "9. gate integration:"
gt="$(cat "$HERE/gate-touched.sh")"
want "gate-touched.sh calls lockfile-lint.sh" "lockfile-lint.sh" "$gt"
case "$gt" in
    *'bash "$HERE/lockfile-lint.sh" || exit 1'*'SPIRA_GATE_SUITES:-on'*)
        ok "lockfile-lint.sh runs before the SPIRA_GATE_SUITES=off early return" ;;
    *) bad "lockfile-lint.sh runs before the SPIRA_GATE_SUITES=off early return" \
        "call site is not ahead of the off-mode exit" ;;
esac
is "lockfile-lint.sh is executable" "0" "$([ -x "$HERE/lockfile-lint.sh" ]; echo $?)"

tl_summary
