#!/usr/bin/env bash
#
# worktree-hooks.sh install <worktree> — arm every git hook inside one aeon's worktree.
#
# WHY THIS EXISTS AS ITS OWN SCRIPT. core.hooksPath names ONE directory, and a
# per-worktree setting OVERRIDES the repo-level one. aeon.sh needed a per-worktree
# pre-commit (the dirty-files guard, which is specific to one session's snapshot), so it
# pointed the worktree at a directory containing that hook and nothing else -- silently
# disarming every other hook in the repository for that worktree.
#
# THE SCAR. On 2026-09-18 an Ops aeon deleted 24 peers' unlanded branches from inside its
# own worktree. A reference-transaction hook was written to refuse exactly that, armed at
# the repo level, verified by a live probe, and reported as protecting the repository. It
# was absent from every aeon worktree -- the only place the deletion has ever happened --
# because of the override above. The probe passed because it was run in the main checkout,
# which is the one place an aeon never works (sp-urifb,
# law-guard-proved-where-the-offender-runs).
#
# COMPOSED FROM THE CANONICAL SET, NEVER A LIST. Every hook is copied out of
# $SPIRA_HOME/hooks, so a hook added there tomorrow is armed in worktrees without anyone
# remembering this file exists. A list is how the next hook gets forgotten the same way
# the last one was.
#
# SEPARATE FROM aeon.sh SO IT CAN BE TESTED. Asserting this property through aeon.sh would
# mean summoning an aeon; test-ref-guard.sh calls this directly instead.
#
# Usage:
#   worktree-hooks.sh install <worktree-path>
#
# Reads SPIRA_HOME (the directory holding hooks/ and pre-commit-guard.sh); defaults to the
# directory this script lives in, so it works in a worktree and in a clone at any path.

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
SPIRA_HOME="${SPIRA_HOME:-$HERE}"

usage() { printf 'usage: worktree-hooks.sh install <worktree-path>\n' >&2; exit 2; }

cmd="${1:-}"
[ "$cmd" = install ] || usage
WORK="${2:-}"
[ -n "$WORK" ] || usage
[ -d "$WORK" ] || { printf 'worktree-hooks: %s is not a directory\n' "$WORK" >&2; exit 1; }

src="$SPIRA_HOME/hooks"
[ -d "$src" ] || { printf 'worktree-hooks: no hooks directory at %s\n' "$src" >&2; exit 1; }

gitdir="$(git -C "$WORK" rev-parse --path-format=absolute --git-dir 2>/dev/null)" || {
    printf 'worktree-hooks: %s is not a git worktree\n' "$WORK" >&2; exit 1; }

dest="$gitdir/hooks"
mkdir -p "$dest" || exit 1

# THE CANONICAL HOOKS FIRST. Files ending in .sh are helpers that live beside the hooks
# (aeon-fence.sh, session.sh) and are not hooks themselves -- git would ignore them anyway,
# but copying them would imply they are armed here, which they are not.
copied=""
for h in "$src"/*; do
    [ -f "$h" ] || continue
    name="$(basename "$h")"
    case "$name" in
        *.sh) continue ;;
        pre-commit) continue ;;   # composed below, not copied
    esac
    cp "$h" "$dest/$name" || exit 1
    chmod +x "$dest/$name" || exit 1
    copied="$copied $name"
done

# PRE-COMMIT IS COMPOSED, NOT REPLACED. The worktree needs BOTH the canonical fences
# (beads data, aeon identity on the base branch) and this session's dirty-files guard.
# Replacing one with the other is what the old code did, so an aeon worktree was also
# running without exclude.sh's and branch-guard.sh's checks.
#
# The canonical hook is invoked BY ITS REAL PATH rather than copied, because it resolves
# its siblings with "$(dirname "$0")/../exclude.sh" -- a copy into the worktree hooks dir
# would look for exclude.sh next to the copy and die "No such file or directory", which
# disarms the guard while leaving it apparently installed. Same reason a symlink is wrong
# here.
cat > "$dest/pre-commit" <<EOF
#!/usr/bin/env bash
# GENERATED by worktree-hooks.sh. Both fences must pass, canonical first.
set -uo pipefail
bash "$src/pre-commit" "\$@" || exit 1
exec bash "$SPIRA_HOME/pre-commit-guard.sh" "\$@"
EOF
chmod +x "$dest/pre-commit" || exit 1
copied="$copied pre-commit"

# `git config --worktree` writes nothing unless the repository declares the extension, and
# it is enabled here rather than assumed so this script is usable on its own. Idempotent
# and additive: a worktree with no config.worktree file behaves exactly as before.
git -C "$WORK" config extensions.worktreeConfig true || exit 1
git -C "$WORK" config --worktree core.hooksPath "$dest" || exit 1

printf 'worktree-hooks: armed in %s:%s\n' "$WORK" "$copied"
